In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pickle as pkl

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
x = np.array([[0, 1, 0, 1]])
y = np.array([[1, 0, 1, 0]])

cosine_similarity(x, y)

array([[0.]])

<br><br>

LSTM output 유효한지 확인

In [20]:
with open('experiment1/true_input_features_sample3.pkl', 'rb+') as f:
    true_input_fatures_sample3 = pkl.load(f)
    
with open('experiment1/true_input_features_sample4.pkl', 'rb+') as f:
    true_input_fatures_sample4 = pkl.load(f)

In [21]:
cosine_similarity(true_input_fatures_sample3.cpu().detach(), true_input_fatures_sample4.cpu().detach())

array([[0.99999857]], dtype=float32)

embedding network(lstm)과 binding network를 한번에 묶어서 학습시키는 경우에 문제가 발생한다.

어찌보면 당연한 결과이다. false 데이터가 없어서 학습이 너무 쉬울 뿐만 아니라

난이도에 비해 파라미터의 수가 너무 많다.

무슨 값을 넣어도 똑같은 값이 나올 수 밖에 없다.

<br>

이렇게 보니 LSTM을 굳이 넣어야 하나... 그냥 잘 학습된 embedding network를 가지고 오면 편할 것 같다.

굳이 쓰자면 LSTM을 어떤 데이터셋을 가지고 학습을 시키는 것인데,

Label이 없어서 비지도 학습이 될 것 같은데

LSTM이 과연 비지도 학습에 효과적인 모델인가?

또 Voxceleb 데이터셋은 외국인 발화 데이터셋이다. 애초에 voxceleb를 쓴다는 것 자체가 task에 맞지 않다.

<br>

In [23]:
with open('experiment2/false_input_features_compare2.pkl', 'rb+') as f:
    false_input_features_compare2 = pkl.load(f)
    
with open('experiment2/false_input_features_compare1.pkl', 'rb+') as f:
    false_input_features_compare1 = pkl.load(f)

In [24]:
cosine_similarity(false_input_features_compare2.cpu().detach(), false_input_features_compare1.cpu().detach())

array([[0.99970496]], dtype=float32)