In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pickle as pkl

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
x = np.array([[0, 1, 0, 1]])
y = np.array([[1, 0, 1, 0]])

cosine_similarity(x, y)

array([[0.]])

<br><br>

LSTM output 유효한지 확인

In [20]:
with open('experiment1/true_input_features_sample3.pkl', 'rb+') as f:
    true_input_fatures_sample3 = pkl.load(f)
    
with open('experiment1/true_input_features_sample4.pkl', 'rb+') as f:
    true_input_fatures_sample4 = pkl.load(f)

In [21]:
cosine_similarity(true_input_fatures_sample3.cpu().detach(), true_input_fatures_sample4.cpu().detach())

array([[0.99999857]], dtype=float32)

In [27]:
with open('experiment1/true_input_features_sample3.pkl', 'rb+') as f:
    true_input_features_sample3 = pkl.load(f)
    
with open('experiment2/false_input_features_compare1.pkl', 'rb+') as f:
    false_input_features_compare1 = pkl.load(f)

In [29]:
cosine_similarity(true_input_features_sample3.cpu().detach(), false_input_features_compare1.cpu().detach())

array([[0.08211382]], dtype=float32)

완전히 다른 embedding vector가 나오는데 왜 output이 항상 같은지 확인 필요